# Generated by Django 4.0.1 on 2022-02-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_profile_assessment_perfected_profile_mock_perfected'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievement',
            field=models.CharField(choices=[('Wheat of Prosperity', 'Wheat of Prosperity'), ('Terracota Helmet', 'Terracota Helmet'), ('Golden Konghou', 'Golden Konghou'), ('Lù Antlers', 'Lù Antlers'), ('Lost Coin of Shihuangdi', 'Lost Coin of Shihuangdi')], default='', max_length=150),
        ),
    ]
