# Generated by Django 4.0.1 on 2022-02-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_profile_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='achievement',
        ),
        migrations.AddField(
            model_name='profile',
            name='lessons_100',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='lessons_25',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='lessons_50',
            field=models.BooleanField(default=False),
        ),
    ]
