# Generated by Django 4.0.1 on 2022-01-28 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsk', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LessonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(max_length=50)),
                ('pinyin', models.CharField(max_length=50)),
                ('english', models.CharField(max_length=255)),
                ('title', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lessonbank.lessonbank')),
            ],
        ),
        migrations.CreateModel(
            name='LessonAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choices', models.TextField()),
                ('answer', models.CharField(max_length=50)),
                ('title', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lessonbank.lessonbank')),
            ],
        ),
    ]
