# Generated by Django 4.0.1 on 2022-01-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonassessment',
            name='question_type',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Fill in the Blanks', 'Fill in the Blanks'), ('True or False', 'True or False')], default='Multiple Choice', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonassessment',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lessonassessment',
            name='choices',
            field=models.TextField(blank=True, null=True),
        ),
    ]
