# Generated by Django 4.0.1 on 2022-01-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonbank', '0002_lessonassessment_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbank',
            name='lesson_number',
            field=models.IntegerField(default=0),
        ),
    ]
