# Generated by Django 4.0.1 on 2022-01-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonbank', '0003_lessonbank_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbank',
            name='lesson_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
