# Generated by Django 4.0.1 on 2022-01-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_profile_image'),
        ('lessonbank', '0008_lessonbank_read_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbank',
            name='read_by',
            field=models.ManyToManyField(blank=True, null=True, to='landing.Profile'),
        ),
    ]
