# Generated by Django 4.0.1 on 2022-02-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonbank', '0010_alter_lessonbank_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonbank',
            name='lesson_number',
        ),
    ]
