# Generated by Django 4.0.1 on 2022-02-01 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonbank', '0011_remove_lessonbank_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbank',
            name='hsk',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
