# Generated by Django 4.0.1 on 2022-02-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonbank', '0013_remove_lessonassessment_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbank',
            name='enable_table',
            field=models.BooleanField(default=True),
        ),
    ]
