# Generated by Django 4.0.1 on 2022-02-02 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonbank', '0014_lessonbank_enable_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonItem',
        ),
    ]
