# Generated by Django 4.0.1 on 2022-02-10 01:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminmode', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLogs',
            new_name='UserLog',
        ),
    ]
