# Generated by Django 4.0.1 on 2022-02-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmode', '0003_alter_userlog_log_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_by', models.CharField(max_length=150)),
                ('achievement', models.CharField(choices=[('Wheat of Prosperity', 'Wheat of Prosperity'), ('Terracota Helmet', 'Terracota Helmet'), ('Golden Konghou', 'Golden Konghou'), ('Lù Antlers', 'Lù Antlers'), ('Lost Coin of Shihuangdi', 'Lost Coin of Shihuangdi')], max_length=150)),
                ('date_time_achieved', models.DateTimeField()),
            ],
        ),
    ]
