# Generated by Django 4.0.1 on 2022-02-10 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminmode', '0004_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achieved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
