# Generated by Django 4.0.1 on 2022-02-10 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminmode', '0005_alter_achievement_achieved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(choices=[('Wheat of Prosperity', 'Wheat of Prosperity'), ('Terracota Helmet', 'Terracota Helmet'), ('Golden Konghou', 'Golden Konghou'), ('Lù Antlers', 'Lù Antlers'), ('Lost Coin of Shihuangdi', 'Lost Coin of Shihuangdi')], max_length=150, null=True)),
                ('date_time_achieved', models.DateTimeField()),
                ('achieved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
