# Generated by Django 4.0.1 on 2022-01-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
