# Generated by Django 4.0.1 on 2022-01-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_dictionary_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
