# Generated by Django 4.0.1 on 2022-02-01 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessonbank', '0011_remove_lessonbank_lesson_number'),
        ('dictionary', '0004_alter_dictionary_part_of_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='from_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessonbank.lessonbank'),
        ),
    ]
