# Generated by Django 4.0.1 on 2022-02-02 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_dictionary_example_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='hsk',
        ),
    ]
